name: paas_dart
description: paas_dart library for make your program dart more easy.
version: 0.0.0
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev


executables:
  paas_dart: paas_dart
  

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  alfred: ^1.1.1
  docker_dart: ^0.0.2
  ffi: ^2.0.2
  general_lib: ^0.0.1
  path: ^1.8.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  msix: ^3.12.1
  packagex: ^0.0.28
  test: ^1.24.2

msix_config: 
  display_name: paas_dart
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.paas_dart
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam

packagex:
  name: paas_dart
  dart_target: paas_dart
  flutter_target: main
  dart_name: paas_dart
  flutter_name: paas_dart
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
