name: paas_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  docker_dart: ^0.0.2
  general_lib: ^0.0.1
  intl: ^0.18.1
  isar: ^3.1.0+1
  path: ^1.8.3
  supabase_client: ^0.0.23
  telegram_client: ^0.5.85
  universal_io: ^2.2.2
  xendit: ^0.0.21
  zxing2: ^0.2.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  lints: ^2.1.0
  test: ^1.24.0
